package uz.gita.a4pisc1word

class GameRepository : GameContract.Model {
    private val data = ArrayList<GameData>()
    override operator fun get(level: Int): GameData {
        return data[level]
    }

    override fun QuustionsSize(): Int {
        return data.size
    }

    init {
        data.add(
            GameData(
                R.drawable.apple,
                R.drawable.apples,
                R.drawable.asalapple,
                R.drawable.iphone,
                "apple",
                "jenoplpajfea"
            )
        )
        data.add(
            GameData(
                R.drawable.banan,
                R.drawable.bananapple,
                R.drawable.banandrink,
                R.drawable.bananicce,
                "banana",
                "aenblajnaezz"
            )
        )
        data.add(
            GameData(
                R.drawable.ice_cream,
                R.drawable.ice_ice,
                R.drawable.ice_kanki,
                R.drawable.ice_muz,
                "ice",
                "iebcmajzkels"
            )
        )
        data.add(
            GameData(
                R.drawable.box_box,
                R.drawable.box_fruit,
                R.drawable.box_hasan,
                R.drawable.box_quti,
                "box",
                "bidoljxnkels"
            )
        )
        data.add(
            GameData(
                R.drawable.ring_hand,
                R.drawable.ring,
                R.drawable.ring_man,
                R.drawable.ring_short,
                "ring",
                "ieurutlgnnke"
            )
        )
        data.add(
            GameData(
                R.drawable.dog,
                R.drawable.dogboy,
                R.drawable.dogs,
                R.drawable.dogcat,
                "pet",
                "jeutlgpzkels"
            )
        )
        data.add(
            GameData(
                R.drawable.horsecheers,
                R.drawable.horseman,
                R.drawable.horsetoy,
                R.drawable.horse,
                "horse",
                "pojehrnzjnks"
            )
        )
        data.add(
            GameData(
                R.drawable.dogit,
                R.drawable.dog_panja,
                R.drawable.dogchaqmoq,
                R.drawable.dogitt,
                "dog",
                "podhrongjnks"
            )
        )
        data.add(
            GameData(
                R.drawable.photos,
                R.drawable.photocam,
                R.drawable.photo,
                R.drawable.dogmikki,
                "photo",
                "podhrongtnks"
            )
        )
        data.add(
            GameData(
                R.drawable.manitorcomp,
                R.drawable.manitor1,
                R.drawable.manitor2,
                R.drawable.manitor3,
                "monitor",
                "pomrongtnisz"
            )
        )
        data.add(
            GameData(
                R.drawable.bird_1,
                R.drawable.bird_2,
                R.drawable.bird_3,
                R.drawable.bird_4,
                "bird",
                "puisubdjynrs"
            )
        )
        data.add(
            GameData(
                R.drawable.gift_1,
                R.drawable.gift_2,
                R.drawable.gift_3,
                R.drawable.gift_4,
                "gift",
                "ssfotidgssya"
            )
        )
        data.add(
            GameData(
                R.drawable.phone_1,
                R.drawable.phone_2,
                R.drawable.phone_3,
                R.drawable.phone_4,
                "phone",
                "fonkpdfnhege"
            )
        )
    }
}
